### ISSUE TITLE
qr code reading

### ISSUE THREAD

**Issue by RiwEZ** [RiwEZ/kibo_lynx#1]
![image](https://user-images.githubusercontent.com/55591062/116235169-b9872f00-a787-11eb-8f6d-e6b9c96d2519.png)

ไม่รู้ position กะ orientation ถูกยัง แต่ภาพ qr code ที่ได้ก็น่าจะประมาณใน NavCam

- วิธีสร้าง Bitmap ให้ zxing อ่าน คล้ายๆกับ ของปีที่แล้ว
https://stackoverflow.com/questions/14861553/zxing-convert-bitmap-to-binarybitmap

- [x] due 04/05/2021

**Comment by PutawanDE** [comment]
Log from the latest simulation (@2021-04-27 14:25:15 UTC)

`04-27 14:40:46.350 I/qr_move ( 3439): Failed reading qr code-- com.google.zxing.NotFoundException`

**Comment by PutawanDE** [comment]
Possible causes
1. Distorted image ,or, and
2. Image resolution is too big.

**Comment by apiphoomchu** [comment]
ดีฮะผมมาลองเเนะนําอะไรใหม่ๆ (ถ้าอยากลองนะครับ)
เช่นการ Crop ตัว Bitmap

Example :
Bitmap bitmap = api.getBitmapNavCam();
Bitmap crop = Bitmap.createBitmap(bitmap,0,0,960,960);

เเล้วก็ return crop Bitmap ส่วนตัว crop ก็สามารถปรับสเกลการ crop ได้ตามใจชอบเลยนะครับ 👍🏻 
โชคดีฮะ

**Comment by PutawanDE** [comment]
Fix Undistorted result is pitch black 3a9a71e5ff9900fb0a96e99dcb2fd865191b1f72 based on a test result of kibo_lynx_test PutawanDE/kibo_lynx_test@4796a9d57a8211ab8a1e4a0bca32b76378056529

Result undistorted image
https://media.discordapp.net/attachments/823472356156375060/837746229260714014/result.png?width=901&height=670

In and Out resolution is the same. 

มีปห.ที่ crop. crop ใหญ่ไปก็ไม่อ่าน crop เล็กไปก็ไม่อ่าน

**Comment by RiwEZ** [comment]
should be working on 2058a6b20746bbc44319166aea421fa8905c8b80
